name: Deploy Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VDS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USERNAME }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          echo "Starting deployment process..."
          cd ~/bot || exit 1
          echo "Pulling latest changes..."
          git pull || exit 1
          echo "Activating virtual environment..."
          source venv/bin/activate || exit 1
          echo "Installing dependencies..."
          pip install -r requirements.txt || exit 1
          echo "Restarting services..."
          sudo systemctl restart telegram-bot
          echo "Checking services status..."
          sudo systemctl status telegram-bot --no-pager
          echo "Deployment completed successfully!" 